In [2]:
import numpy as np
import pandas as pd
import os

In [3]:
import numpy as np
docs = "Can I eat the Pizza".lower().split()
doc1 = set(docs)
doc1 = sorted(doc1)
print ("\nvalues: ", doc1)


values:  ['can', 'eat', 'i', 'pizza', 'the']


In [4]:
integer_encoded = []
for i in docs:
    v = np.where( np.array(doc1) == i)[0][0]
    integer_encoded.append(v)
print ("\ninteger encoded: ",integer_encoded)


integer encoded:  [0, 2, 1, 4, 3]


In [5]:
def get_vec(len_doc,word):
    empty_vector = [0] * len_doc
    vect = 0
    find = np.where( np.array(doc1) == word)[0][0]
    empty_vector[find] = 1
    return empty_vector

def get_matrix(doc1):
    mat = []
    len_doc = len(doc1)
    for i in docs:
        vec = get_vec(len_doc,i)
        mat.append(vec)

    return np.asarray(mat)

print ("\nMATRIX:")
print (get_matrix(doc1))


MATRIX:
[[1 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]]


In [6]:
import numpy as np

docs = "Can I eat the Pizza".lower()
doc1 = set(docs)
doc1 = sorted(doc1)

print("\nvalues: ", doc1)

integer_encoded = []
for i in docs:
    v = np.where(np.array(doc1) == i)[0][0]
    integer_encoded.append(v)

print("\ninteger encoded: ", integer_encoded)


def get_vec(len_doc, char):
    empty_vector = [0] * len_doc
    find = np.where(np.array(doc1) == char)[0][0]
    empty_vector[find] = 1
    return empty_vector


def get_matrix(doc1):
    mat = []
    len_doc = len(doc1)
    for i in docs:
        vec = get_vec(len_doc, i)
        mat.append(vec)

    return np.asarray(mat)

print("\nMATRIX:")
print(get_matrix(doc1))



values:  [' ', 'a', 'c', 'e', 'h', 'i', 'n', 'p', 't', 'z']

integer encoded:  [2, 1, 6, 0, 5, 0, 3, 1, 8, 0, 8, 4, 3, 0, 7, 5, 9, 9, 1]

MATRIX:
[[0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 0 0]]


In [9]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Sample list of words
words = ['apple', 'banana', 'orange']

# Create a character vocabulary
chars = set(''.join(words))
char_vocab_size = len(chars)

# Create a character-to-index mapping
char_to_index = {char: index for index, char in enumerate(chars)}

# Encode characters using label encoding
encoded_words = [[char_to_index[char] for char in word] for word in words]

# Convert encoded_words to a 2D array of strings
encoded_words = np.array([''.join(map(str, word)) for word in encoded_words]).reshape(-1, 1)

# Perform one-hot encoding on character sequences
encoder = OneHotEncoder(categories='auto', sparse=False)
onehot_encoded_words = encoder.fit_transform(encoded_words)

print(onehot_encoded_words)


[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [10]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical

# Sample text data
texts = ["one hot encoding example", "word embedding tutorial", "character one-hot"]

# Tokenize words
tokenizer_word = Tokenizer()
tokenizer_word.fit_on_texts(texts)

# One-hot encode words
sequences_word = tokenizer_word.texts_to_sequences(texts)
one_hot_word = tokenizer_word.sequences_to_matrix(sequences_word, mode='binary')

# Tokenize characters
tokenizer_char = Tokenizer(char_level=True)
tokenizer_char.fit_on_texts(texts)

# One-hot encode characters
sequences_char = tokenizer_char.texts_to_sequences(texts)
one_hot_char = tokenizer_char.sequences_to_matrix(sequences_char, mode='binary')

# Print results
print("One-hot encoding of words:")
print(one_hot_word)

print("\nOne-hot encoding of characters:")
print(one_hot_char)


One-hot encoding of words:
[[0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 1.]]

One-hot encoding of characters:
[[0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
